C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.14 (r7260) - 18 Jan 2019 10:11
C
C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.14 (r7260) - 18 Jan 2019 10:11
C
C  Differentiation of update in reverse (adjoint) mode:
C   gradient     of useful results: g
C   with respect to varying inputs: g x1 x2
C   RW status of diff variables: g:in-zero x1:out x2:out
C!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
C
C
C
      SUBROUTINE UPDATE_B(x1, x1b, x2, x2b, g, gb, gx, gy)
      IMPLICIT NONE
C
C
      DOUBLE PRECISION x1, x2, g, gx, gy
      DOUBLE PRECISION x1b, x2b, gb
      INTRINSIC SIN
      INTRINSIC COS
C
C
      DOUBLE PRECISION tempb
      tempb = x1*COS(x1*x2)*gb
      x1b = x2*tempb + SIN(x1*x2)*gb
      x2b = gb + x1*tempb
      gb = 0.D0
      END


