C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.14 (r7260) - 18 Jan 2019 10:11
C
C  Differentiation of f in forward (tangent) mode:
C   variations   of useful results: f
C   with respect to varying inputs: t
      DOUBLE PRECISION FUNCTION F_D(t, td, f)
      IMPLICIT NONE
      DOUBLE PRECISION t
      DOUBLE PRECISION td
      INTRINSIC EXP
      DOUBLE PRECISION f
      f_d = (td*t+t*td)*EXP(t*t)
      f = EXP(t*t)
      RETURN
      END

C  Differentiation of g in forward (tangent) mode:
C   variations   of useful results: g
C   with respect to varying inputs: t
C
      DOUBLE PRECISION FUNCTION G_D(t, td, g)
      IMPLICIT NONE
      DOUBLE PRECISION t
      DOUBLE PRECISION td
      INTRINSIC SIN
      DOUBLE PRECISION g
      g = 1
      IF (t .NE. 0.d0) THEN
        g_d = (td*COS(t)*t-SIN(t)*td)/t**2
        g = SIN(t)/t
      ELSE
        g_d = 0.D0
      END IF
      RETURN
      END

